######################################################################
# Automatically generated by qmake (3.1) Mon May 22 18:51:27 2017
######################################################################

TEMPLATE = app
TARGET = Reminder
INCLUDEPATH += .

CONFIG += link_pkgconfig
PKGCONFIG += libnotify

# Input
SOURCES += main.cpp
QT += widgets
